const GithubIcon = ({ size = 17 }: { size?: number }) => <svg aria-hidden="true" width={size} height={size} viewBox="0 0 24 24" fill="currentColor"><path d="M12 .7a12 12 0 0 0-3.79 23.4c.6.11.82-.26.82-.58v-2.03c-3.34.73-4.04-1.61-4.04-1.61-.55-1.4-1.34-1.77-1.34-1.77-1.09-.75.08-.74.08-.74 1.2.08 1.84 1.23 1.84 1.23 1.07 1.83 2.8 1.3 3.48.99.11-.77.42-1.3.76-1.6-2.67-.3-5.47-1.34-5.47-5.93 0-1.31.47-2.38 1.23-3.22-.12-.3-.53-1.52.12-3.17 0 0 1.01-.32 3.3 1.23a11.46 11.46 0 0 1 6-.81 11.5 11.5 0 0 1 6 .81c2.29-1.55 3.3-1.23 3.3-1.23.65 1.65.24 2.87.12 3.17.76.84 1.23 1.91 1.23 3.22 0 4.6-2.8 5.63-5.48 5.92.43.37.81 1.1.81 2.22v3.29c0 .32.22.69.83.57A12 12 0 0 0 12 .7Z"/></svg>;
const LinkedInIcon = ({ size = 17 }: { size?: number }) => <svg aria-hidden="true" width={size} height={size} viewBox="0 0 24 24" fill="currentColor"><path d="M4.98 3.5a2.5 2.5 0 1 1 0 5.001 2.5 2.5 0 0 1 0-5.001ZM2.75 9.25h4.46V21.5H2.75V9.25Zm7.25 0h4.28v1.68h.06c.6-1.14 2.06-2.34 4.24-2.34 4.53 0 5.37 2.98 5.37 6.86v6.05h-4.46v-5.36c0-1.28-.02-2.93-1.79-2.93-1.79 0-2.07 1.4-2.07 2.84v5.45H10V9.25Z"/></svg>;
const Arrow = ({ direction = "right" }: { direction?: "right" | "up" | "down" }) => <svg aria-hidden="true" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={direction === "down" ? "M5 5l14 14M19 10v9h-9" : direction === "up" ? "M5 19L19 5M10 5h9v9" : "M5 12h14M13 6l6 6-6 6"}/></svg>;
const MailIcon = () => <svg aria-hidden="true" width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/></svg>;
const Dot = () => <span aria-hidden="true" className="h-2 w-2 rounded-full bg-[#d6ff00]" />;

const skills = ["Machine Learning", "Ensemble Methods", "Time Series", "Data Visualization", "Power BI", "PySpark", "Azure Databricks", "Data Analysis", "Keras / TensorFlow", "Deep Learning", "Classification", "Forecasting"];
const projects = [
  { index: "01", title: "Outlet-SKU Universe & Clustering", description: "Defined and scoped the Outlet-SKU universe for POG and non-POG retailers, using dimensionality reduction and clustering to focus analysis on high-impact segments.", tags: ["PCA", "Clustering", "Retail Analytics"] },
  { index: "02", title: "Predictive Sales Modelling", description: "Built predictive sales models to estimate baseline volume across outlets and SKUs using POS sales and historical trends, then connected outputs to downstream planning.", tags: ["Forecasting", "Machine Learning", "POS Data"] },
  { index: "03", title: "Display Optimization Framework", description: "Built an end-to-end display planning pipeline to identify high-potential outlets and forecast uplift, with architecture for distribution sell-in recommendations.", tags: ["Optimization", "Pipeline", "Recommendations"] },
];
const experience = [
  { period: "AUG 2024 — PRESENT", role: "Senior Data Scientist", company: "Sigmoid Analytics", details: ["Outlet-SKU universe definition and high-impact segmentation for POG and non-POG retailers.", "PCA across 30+ features, capturing 80%+ of data variance for efficient clustering.", "Predictive sales modelling and integration into display planning, compliance tracking and sell-in simulations.", "Display planning and pre-display forecast architecture for field broker recommendations."] },
  { period: "OCT 2020 — AUG 2024", role: "Data Science Consultant", company: "", details: ["Worked with clients to understand data science requirements and build tailored solutions.", "Built predictive models to automate demand forecasting processes.", "Improved existing model accuracy by 15%–20% through feature engineering and selection.", "Owned projects end-to-end across acquisition, cleaning, modelling, deployment and reporting.", "Created Power BI views of machine-learning model performance metrics."] },
];

export default function Portfolio() {
  return <main id="top" className="grain min-h-screen bg-[#070707] text-[#f5f5f2]">
    <nav className="fixed left-0 right-0 top-0 z-50 border-b border-white/10 bg-black/45 px-5 backdrop-blur-xl md:px-10"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between"><a href="#top" className="font-display text-sm font-semibold uppercase tracking-[0.2em]">AY<span className="text-[#d6ff00]">.</span></a><div className="hidden gap-8 text-xs uppercase tracking-[0.18em] text-white/55 md:flex"><a href="#work" className="transition hover:text-white">Work</a><a href="#about" className="transition hover:text-white">About</a><a href="#experience" className="transition hover:text-white">Experience</a><a href="#contact" className="transition hover:text-white">Contact</a></div><a href="#contact" className="rounded-full border border-white/15 px-4 py-2 text-xs uppercase tracking-[0.16em] transition hover:border-[#d6ff00] hover:text-[#d6ff00]">Let’s talk</a></div></nav>
    <section className="grid-bg relative flex min-h-screen items-end overflow-hidden px-5 pb-20 pt-32 md:px-10 md:pb-24"><div className="hero-glow right-[-12rem] top-[10rem]"/><div className="mx-auto w-full max-w-7xl"><div className="hero-reveal mb-7 flex items-center gap-3 text-xs uppercase tracking-[0.22em] text-white/45"><Dot/> Available for interesting problems</div><h1 className="hero-reveal-delay font-display text-[15vw] leading-[.8] tracking-[-.075em] md:text-[9.6rem]">ADITYA<br/>KUMAR<br/><span className="text-white/25">YADAV</span></h1><div className="mt-12 grid gap-8 border-t border-white/10 pt-7 md:grid-cols-[1fr_auto] md:items-end"><p className="hero-reveal-delay-2 max-w-2xl text-lg leading-relaxed text-white/60 md:text-2xl">Senior Data Scientist building practical systems across <span className="text-white">machine learning, analytics, forecasting and data engineering.</span></p><a href="#work" className="group flex items-center gap-4 text-sm uppercase tracking-[.18em]">Explore work<span className="flex h-12 w-12 items-center justify-center rounded-full border border-white/15 transition duration-300 group-hover:border-[#d6ff00] group-hover:text-[#d6ff00]"><Arrow direction="down"/></span></a></div></div></section>
    <section id="about" className="border-t border-white/10 px-5 py-28 md:px-10 md:py-40"><div className="mx-auto grid max-w-7xl gap-16 md:grid-cols-[220px_1fr]"><div className="text-xs uppercase tracking-[.2em] text-white/35">01 / About</div><div><p className="reveal max-w-5xl font-display text-4xl leading-[1.05] tracking-[-.04em] md:text-7xl">I turn messy data into <span className="text-white/35">clear decisions</span> — combining analytical thinking with production-minded engineering.</p><p className="reveal reveal-delay mt-12 max-w-3xl text-base leading-8 text-white/50 md:text-lg">My current work spans retail analytics, predictive sales, outlet-SKU segmentation, display optimization and downstream decision systems. I enjoy taking ambiguous business problems and turning them into measurable, usable solutions.</p></div></div></section>
    <section id="work" className="px-5 py-20 md:px-10 md:py-32"><div className="mx-auto max-w-7xl"><div className="mb-12 flex items-end justify-between border-b border-white/10 pb-6"><div><div className="text-xs uppercase tracking-[.2em] text-white/35">02 / Selected work</div><h2 className="font-display mt-3 text-4xl tracking-[-.04em] md:text-6xl">Things I’ve built</h2></div><div className="hidden text-xs uppercase tracking-[.18em] text-white/30 md:block">2020—Now</div></div><div className="space-y-4">{projects.map(p=><article key={p.index} className="reveal group rounded-[2rem] border border-white/10 bg-white/[.02] p-6 transition duration-500 hover:-translate-y-1 hover:border-white/20 hover:bg-white/[.045]"><div className="grid gap-8 md:grid-cols-[80px_1fr_auto] md:items-start"><div className="font-display text-sm text-white/25">{p.index}</div><div><h3 className="font-display text-3xl tracking-[-.03em] md:text-5xl">{p.title}</h3><p className="mt-5 max-w-3xl text-base leading-7 text-white/50 md:text-lg">{p.description}</p><div className="mt-7 flex flex-wrap gap-2">{p.tags.map(t=><span key={t} className="rounded-full border border-white/10 px-3 py-1.5 text-xs text-white/45">{t}</span>)}</div></div><div className="flex h-11 w-11 items-center justify-center self-end rounded-full border border-white/10 transition duration-300 group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:border-[#d6ff00] group-hover:text-[#d6ff00]"><Arrow direction="up"/></div></div></article>)}</div></div></section>
    <section className="border-y border-white/10 px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-7xl"><div className="text-xs uppercase tracking-[.2em] text-white/35">03 / Capabilities</div><div className="mt-10 grid gap-2 md:grid-cols-3">{skills.map((s,i)=><div key={s} className="group border-b border-white/10 py-5 text-lg text-white/70 transition duration-300 hover:translate-x-2 hover:text-white md:text-xl"><span className="mr-4 text-xs text-[#d6ff00]">{String(i+1).padStart(2,"0")}</span>{s}</div>)}</div></div></section>
    <section id="experience" className="px-5 py-24 md:px-10 md:py-36"><div className="mx-auto grid max-w-7xl gap-14 md:grid-cols-[220px_1fr]"><div className="text-xs uppercase tracking-[.2em] text-white/35">04 / Experience</div><div className="space-y-16">{experience.map(e=><div key={e.period} className="reveal grid gap-6 border-b border-white/10 pb-16 md:grid-cols-[220px_1fr]"><div className="text-xs uppercase tracking-[.16em] text-white/35">{e.period}</div><div><h3 className="font-display text-3xl tracking-[-.03em] md:text-4xl">{e.role}</h3>{e.company&&<div className="mt-1 text-sm text-[#d6ff00]">{e.company}</div>}<div className="mt-7 space-y-3">{e.details.map(d=><p key={d} className="max-w-3xl leading-7 text-white/50">{d}</p>)}</div></div></div>)}</div></div></section>
    <section className="bg-[#d6ff00] px-5 py-16 text-black md:px-10 md:py-24"><div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-3"><div><div className="text-xs uppercase tracking-[.18em] opacity-55">Experience</div><div className="mt-2 font-display text-5xl tracking-[-.05em]">5+ years</div></div><div><div className="text-xs uppercase tracking-[.18em] opacity-55">Model impact</div><div className="mt-2 font-display text-5xl tracking-[-.05em]">15–20%</div><div className="mt-1 text-sm opacity-65">accuracy improvement in prior models</div></div><div><div className="text-xs uppercase tracking-[.18em] opacity-55">Variance captured</div><div className="mt-2 font-display text-5xl tracking-[-.05em]">80%+</div><div className="mt-1 text-sm opacity-65">with PCA across 30+ features</div></div></div></section>
    <section id="contact" className="px-5 py-28 md:px-10 md:py-44"><div className="mx-auto max-w-7xl"><div className="text-xs uppercase tracking-[.2em] text-white/35">05 / Contact</div><h2 className="reveal mt-8 max-w-5xl font-display text-6xl leading-[.9] tracking-[-.06em] md:text-[8rem]">LET’S BUILD<br/><span className="text-white/25">SOMETHING USEFUL.</span></h2><div className="mt-16 flex flex-wrap gap-3"><a href="mailto:aditya@example.com" className="flex items-center gap-3 rounded-full bg-[#f5f5f2] px-5 py-3 text-sm font-medium text-black transition hover:scale-[1.02]"><MailIcon/> Email</a><a href="https://github.com/adityaky1999" target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-full border border-white/15 px-5 py-3 text-sm transition hover:border-white/40"><GithubIcon/> GitHub</a><a href="https://www.linkedin.com" target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-full border border-white/15 px-5 py-3 text-sm transition hover:border-white/40"><LinkedInIcon/> LinkedIn</a></div><div className="mt-24 flex items-center justify-between border-t border-white/10 pt-6 text-xs uppercase tracking-[.15em] text-white/30"><span>Aditya Kumar Yadav</span><a href="#top" className="flex items-center gap-2 transition hover:text-white">Back to top <Arrow direction="up"/></a></div></div></section>
  </main>;
}
